/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import nuclearPlant.elements.Reactor;

/**
 *
 * @author nata_
 */
public class plantManagement extends javax.swing.JFrame {
    
    Reactor reactor = new Reactor();
    ImageIcon iconOn = new ImageIcon("src/Images/on.png");
    ImageIcon iconOff = new ImageIcon("src/Images/off.png");
    /**
     * Creates new form plantManagement
     */
    public plantManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btncargar = new javax.swing.JButton();
        btndescargar = new javax.swing.JButton();
        txtCarga = new javax.swing.JTextField();
        txtDescarga = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        pbCarga = new javax.swing.JProgressBar();
        onOff = new javax.swing.JToggleButton();
        jLabel7 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JTextField();
        btnReparar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel3.setText("Acciones en reactor");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(260, 90, 280, 29);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Carga");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 310, 70, 30);

        btncargar.setText("Cargar");
        btncargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncargarActionPerformed(evt);
            }
        });
        getContentPane().add(btncargar);
        btncargar.setBounds(20, 150, 100, 40);

        btndescargar.setText("Descargar");
        btndescargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndescargarActionPerformed(evt);
            }
        });
        getContentPane().add(btndescargar);
        btndescargar.setBounds(20, 210, 100, 40);
        getContentPane().add(txtCarga);
        txtCarga.setBounds(190, 150, 80, 40);
        getContentPane().add(txtDescarga);
        txtDescarga.setBounds(190, 210, 80, 40);

        jLabel5.setText("%");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(270, 150, 20, 30);

        pbCarga.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pbCarga.setForeground(new java.awt.Color(0, 0, 0));
        pbCarga.setToolTipText("");
        pbCarga.setStringPainted(true);
        getContentPane().add(pbCarga);
        pbCarga.setBounds(100, 300, 640, 50);

        onOff.setForeground(new java.awt.Color(255, 255, 255));
        onOff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/off.png"))); // NOI18N
        onOff.setBorderPainted(false);
        onOff.setContentAreaFilled(false);
        onOff.setOpaque(true);
        onOff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onOffActionPerformed(evt);
            }
        });
        getContentPane().add(onOff);
        onOff.setBounds(580, 90, 70, 37);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Estado");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(450, 150, 60, 22);

        txtEstado.setEditable(false);
        txtEstado.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtEstado.setForeground(new java.awt.Color(51, 255, 0));
        txtEstado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtEstado.setName("Funcional"); // NOI18N
        txtEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEstadoActionPerformed(evt);
            }
        });
        getContentPane().add(txtEstado);
        txtEstado.setBounds(530, 150, 180, 30);

        btnReparar.setText("Reparar");
        btnReparar.setEnabled(false);
        btnReparar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepararActionPerformed(evt);
            }
        });
        getContentPane().add(btnReparar);
        btnReparar.setBounds(530, 210, 180, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/carga.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(140, 150, 37, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/descarga.png"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(140, 210, 37, 30);

        jLabel6.setText("%");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(270, 210, 20, 30);

        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar);
        btnCerrar.setBounds(310, 380, 120, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logo.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 260, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/fondo.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -10, 780, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncargarActionPerformed
        try{
            if(Integer.parseInt(txtCarga.getText()) < 0) {
                JOptionPane.showMessageDialog(null, "El valor ingresado no es válido", "Error", JOptionPane.INFORMATION_MESSAGE);
            }else {
                reactor.chargeReactor(Integer.parseInt(txtCarga.getText()));
                System.out.println(reactor.getCharge());
                pbCarga.setValue(reactor.getCharge());
                pbCarga.setString(reactor.getCharge() + "%");
                if(reactor.getCharge()>100){
                    JOptionPane.showMessageDialog(null, "¡Se ha dañado el reactor!", "Error", JOptionPane.ERROR_MESSAGE);
                    pbCarga.setString("!");
                    pbCarga.setValue(0);
                    txtEstado.setText(reactor.getState().getLabel());
                    System.out.println(reactor.getState().getLabel());
                    onOff.setEnabled(false);
                    btncargar.setEnabled(false);
                    btndescargar.setEnabled(false);
                    txtCarga.setEditable(false);
                    txtDescarga.setEditable(false);
                    txtEstado.setForeground(Color.red);
                    pbCarga.setForeground(Color.red);
                    btnReparar.setEnabled(true);
                }
            }
        }
        catch(NumberFormatException e){
            if(reactor.isSwitchedOn()==false){
                JOptionPane.showMessageDialog(null, "Debe encender el reactor e ingresar un valor", "Error: campo vacío", JOptionPane.ERROR_MESSAGE);
            }
            else {
                JOptionPane.showMessageDialog(null, "Debe ingresar un valor", "Error: campo vacío", JOptionPane.ERROR_MESSAGE);
            }
            
        } 
        txtCarga.setText(null);
    }//GEN-LAST:event_btncargarActionPerformed

    private void btndescargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndescargarActionPerformed
        try{
            if(Integer.parseInt(txtDescarga.getText()) < 0) {
                JOptionPane.showMessageDialog(null, "Valor requerido", "Error", JOptionPane.INFORMATION_MESSAGE);
            }
            else{
                reactor.dischargeReactor(Integer.parseInt(txtDescarga.getText()));
                System.out.println(reactor.getCharge());
                pbCarga.setValue(reactor.getCharge());
                pbCarga.setString(reactor.getCharge() + "%");
            }
        }catch(NumberFormatException e){
            if(reactor.isSwitchedOn()==false){
                JOptionPane.showMessageDialog(null, "Debe encender el reactor e ingresar un valor, el campo no debe estar vacío", "Error: campo vacío", JOptionPane.ERROR_MESSAGE);
            }
            else {
                JOptionPane.showMessageDialog(null, "Debe ingresar un valor, el campo no debe estar vacío", "Error: campo vacío", JOptionPane.ERROR_MESSAGE);
            }
            
        } 
        txtDescarga.setText(null);     
    }//GEN-LAST:event_btndescargarActionPerformed

    private void onOffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onOffActionPerformed

        if (onOff.isSelected()){
            onOff.setIcon(iconOn);
            reactor.turnOn();
            txtEstado.setText(reactor.getState().getLabel());
            System.out.println(reactor.isSwitchedOn());
        }
        else {
            onOff.setIcon(iconOff);
            reactor.turnOff();
            System.out.println(reactor.isSwitchedOn());
            txtEstado.setText(null);
            reactor.setCharge(0);
            pbCarga.setValue(reactor.getCharge());
            pbCarga.setString(reactor.getCharge() + "%");
        }

    }//GEN-LAST:event_onOffActionPerformed

    private void txtEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEstadoActionPerformed

    }//GEN-LAST:event_txtEstadoActionPerformed

    private void btnRepararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepararActionPerformed
            reactor.repair();
            txtEstado.setText(reactor.getState().getLabel());
            reactor.setCharge(0);
            pbCarga.setString(reactor.getCharge() + "%");
            pbCarga.setValue(reactor.getCharge());
            onOff.setEnabled(true);
            txtEstado.setForeground(Color.green);
            pbCarga.setForeground(Color.black);
            btncargar.setEnabled(true);
            btndescargar.setEnabled(true);
            txtCarga.setEditable(true);
            txtDescarga.setEditable(true);
            btnReparar.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Reactor reparado", "Error", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnRepararActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(plantManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(plantManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(plantManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(plantManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {          
                plantManagement management = new plantManagement();
                management.setVisible(true);                
                management.setBounds(WIDTH, WIDTH, 782, 442);
                
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnReparar;
    private javax.swing.JButton btncargar;
    private javax.swing.JButton btndescargar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton onOff;
    private javax.swing.JProgressBar pbCarga;
    private javax.swing.JTextField txtCarga;
    private javax.swing.JTextField txtDescarga;
    private javax.swing.JTextField txtEstado;
    // End of variables declaration//GEN-END:variables
}
